server.port=7777
spring.application.name=ChatServer


spring.datasource.url=jdbc:mysql://localhost:3306/chat
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update